# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Alchemy tests

on:
  push:
    branches: [ dev ]
    paths:
    - 'packages/alchemy/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'packages/alchemy/**'

jobs:
  lerna:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.18.4
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.4'

    - run: npm install
    - run: npm run lerna bootstrap

  alchemy:
    runs-on: ubuntu-latest
    needs: lerna
    defaults:
      run:
        working-directory: packages/alchemy

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
    - name: Use Node.js 12.18.4
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.4'
    - run: npm ci

#    - run: ./test-ci.sh

    - uses: nanasess/setup-chromedriver@master
      with:
        # Optional: do not specify to match Chrome's version
        chromedriver-version: '89.0.4389.23'
    - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional


    - run: npm run test:integration -- --forceExit
