# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Arc tests

on:
  push:
    branches: [ dev ]
    paths:
    - 'packages/arc/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'packages/arc/**'

jobs:
  lerna:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.18.4
      uses: actions/setup-node@v1
      with:
        node-version: '12.18.4'

    - run: npm install
    - run: npm run lerna bootstrap

  arc:
    runs-on: ubuntu-latest
    needs: lerna
    defaults:
      run:
        working-directory: packages/arc

    env:
      COVERALLS_REPO_TOKEN: JSb4W0aTkLE2jYkJCW6nj5IRx7IQ028sT 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.5
      uses: actions/setup-node@v1
      with:
        node-version: '14.5'

    - run: ./test-ci.sh


    # Temporarily disabled coveralls as it is problematic
    # - name: Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     path-to-lcov: ${{ github.workspace }}/packages/arc/coverage/lcov.info
    #     flag-name: 'Arc'
    #     base-path: ${{ github.workspace }}/packages/arc
  