# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
    paths:
    - 'packages/infra'
  pull_request:
    branches: [ dev ]

jobs:
  infra:

    runs-on: ubuntu-latest

    env:
      COVERALLS_REPO_TOKEN: JSb4W0aTkLE2jYkJCW6nj5IRx7IQ028sT 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.5
      uses: actions/setup-node@v1
      with:
        node-version: '14.5'
    - run: yarn install
    - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - run: if git diff --name-only "origin/main" | sort -u | uniq | grep "packages/infra/" > /dev/null; then cd packages/infra && ./test-ci.sh && cd ../..;fi
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/packages/infra/coverage/lcov.info
        flag-name: 'Infra'
        base-path: ${{ github.workspace }}/packages/infra
