# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Subgraph tests

on:
  push:
    branches: [ dev ]
    paths:
    - 'packages/subgraph/**'
  pull_request:
    branches: [ dev ]
    paths:
    - 'packages/subgraph/**'

jobs:

  subgraph:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/subgraph

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.16
      uses: actions/setup-node@v1
      with:
        node-version: '10.16'
    - run: yarn install
    - run: ./test-ci.sh
